version: '3.5'

services:

  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    entrypoint: ['sh', 'run-django.sh']
    depends_on:
      - db

  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sidia
    ports:
      - "5433:5432"
    volumes:
      - sidia-data-prod:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  sidia-data-prod: